baseURL = 'https://joonasnuutinen.github.io/ilmastoloki'
languageCode = 'fi-FI'
title = 'Ilmastoloki'
theme = 'ananke'

DefaultContentLanguage = "fi"

[params]
  body_classes = "ma0 avenir bg-near-black"
  post_content_classes = "avenir"
  text_color = "near-white"
